# Copyright (C) 1993, 1994, Russell Lang.  All rights reserved.
#  
# This file is part of GSview.
#  
# This program is distributed with NO WARRANTY OF ANY KIND.  No author
# or distributor accepts any responsibility for the consequences of using it,
# or for whether it serves any particular purpose or works at all, unless he
# or she says so in writing.  Refer to the GSview Free Public Licence 
# (the "Licence") for full details.
#  
# Every copy of GSview must include a copy of the Licence, normally in a 
# plain ASCII text file named LICENCE.  The Licence grants you the right 
# to copy, modify and redistribute GSview, but only under certain conditions 
# described in the Licence.  Among other things, the Licence requires that 
# the copyright notice and this notice be preserved on all copies.

# makefile.tc
# EPSTOOL

# Edit COMPBASE and WIN32 as required
COMPBASE = c:\bc45
# WIN32=1 for Win32 version (untested)
WIN32=1
# DEBUG=1 for debugging
DEBUG=0

# Shouldn't need editing below here
COMPDIR = $(COMPBASE)\bin
INCDIR = $(COMPBASE)\include
LIBDIR = $(COMPBASE)\lib
!if $(WIN32)
WINEXT=32
CC = bcc32
CCAUX = bcc
MODEL=32
CFLAGS=-v -w -DMSDOS -DEPSTOOL -I$(INCDIR) -I..\src
!if $(DEBUG)
DEBUGLNK=-v
!endif
STRIP=tdstrp32
!else
WINEXT=
CC = bcc
CCAUX = bcc
MODEL=l
CFLAGS=-v -m$(MODEL) -h -w -DMSDOS -DEPSTOOL -I$(INCDIR) -I..\src
!if $(DEBUG)
DEBUGLNK=/v
!endif
STRIP=tdstrip
!endif
OBJS=epstool.obj ps.obj gvceps.obj

all: epstool.exe

.c.obj:
	$(COMPDIR)\$(CC) -c $(CFLAGS) {$< }

	
epstool.exe: $(OBJS)
!if $(WIN32)
	$(COMPDIR)\$(CC) $(DEBUGLNK) $(OBJS)
!else
	$(COMPDIR)\tlink /Tde /c /m /s /v /l @&&!
$(LIBDIR)\c0$(MODEL) +
$(OBJS) +
,epstool.exe,epstool, +
$(LIBDIR)\math$(MODEL) +
$(LIBDIR)\emu +
$(LIBDIR)\c$(MODEL)
!
!endif

epstool.obj: epstool.c epstool.h ../src/ps.h ../src/gvceps.c

ps.obj: ../src/ps.c epstool.h ../src/ps.h ../src/gvceps.c
	$(COMPDIR)\$(CC) -c $(CFLAGS) ../src/ps.c

gvceps.obj: ../src/gvceps.c epstool.h ../src/ps.h
	$(COMPDIR)\$(CC) -c $(CFLAGS) ../src/gvceps.c


clean:
	-del epstool.obj
	-del ps.obj
	-del gvceps.obj

EPSFILES1=\
 epstool/epstool.c\
 epstool/epstool.h\
 epstool/epstool.def\
 epstool/epstool.doc

EPSFILES2=\
 epstool/epstest.cmd\
 epstool/makefile.os2\
 epstool/makefile.tc\
 epstool/makefile.unx

SRCFILES1=\
 src/LICENCE\
 src/gvceps.c\
 src/gvceps.h\
 src/PUBLIC\
 src/ps.c\
 src/ps.h

ZIPFILES=\
 epstool.exe\
 epstool.doc\
 $(EPSFILES)\
 $(SRCFILES1)

zip: all
	copy epstool.doc ..
	copy epstool.exe ..
	$(STRIP) ..\epstool.exe
	cd ..
	-del epstool.zip
	echo epstool.exe > zipfiles.txt
	echo epstool.doc >> zipfiles.txt
	echo $(EPSFILES1) >> zipfiles.txt
	echo $(EPSFILES2) >> zipfiles.txt
	echo $(SRCFILES1) >> zipfiles.txt
	zip -@ epstool < zipfiles.txt
	del zipfiles.txt
	cd epstool

tar:	zip
	unzip -o ..\epstool
	copy src\* epstool
	-del ..\epstool.tar
	cd epstool
	flip -u *
	cd ..
	tar -cvf ../epstool.tar epstool
