# Copyright (C) 1993-1998, Ghostgum Software Pty Ltd.  All rights reserved.
#  
# This file is part of GSview.
#  
# This program is distributed with NO WARRANTY OF ANY KIND.  No author
# or distributor accepts any responsibility for the consequences of using it,
# or for whether it serves any particular purpose or works at all, unless he
# or she says so in writing.  Refer to the GSview Free Public Licence 
# (the "Licence") for full details.
#  
# Every copy of GSview must include a copy of the Licence, normally in a 
# plain ASCII text file named LICENCE.  The Licence grants you the right 
# to copy, modify and redistribute GSview, but only under certain conditions 
# described in the Licence.  Among other things, the Licence requires that 
# the copyright notice and this notice be preserved on all copies.

# makefile.unx
# EPSTOOL

RM=/bin/rm -f
SHELL=/bin/sh

BINDIR=/usr/local/bin
INCLUDES=-I/usr/openwin/include -I../src -I.
LIBS=
# if you have a strict ANSI compiler, add -D__STDC__
DEFINES=-DUNIX -DEPSTOOL -DHAVE_UNISTD_H
OBJ=o
CC=gcc

OBJS=epstool.$(OBJ) gvceps.$(OBJ) dscparse.$(OBJ) dscutil.$(OBJ)

all: epstool

.cpp.$(OBJ):
	$(CC) $(CFLAGS) $(INCLUDES) $(DEFINES) -c $*.cpp


epstool.$(OBJ): epstool.cpp epstool.h ../src/dscparse.h ../src/gvceps.h
	$(CC) $(CFLAGS) $(INCLUDES) $(DEFINES) -c epstool.cpp -o epstool.$(OBJ)

dscparse.$(OBJ): ../src/dscparse.cpp epstool.h ../src/dscparse.h ../src/gvceps.h
	$(CC) $(CFLAGS) $(INCLUDES) $(DEFINES) -c ../src/dscparse.cpp -o dscparse.$(OBJ)

dscutil.$(OBJ): ../src/dscutil.cpp ../src/dscparse.h
	$(CC) $(CFLAGS) $(INCLUDES) $(DEFINES) -c ../src/dscutil.cpp -o dscutil.$(OBJ)

gvceps.$(OBJ): ../src/gvceps.cpp epstool.h ../src/dscparse.h ../src/gvceps.h
	$(CC) $(CFLAGS) $(INCLUDES) $(DEFINES) -c ../src/gvceps.cpp -o gvceps.$(OBJ)

epstool: $(OBJS)
	$(CC) $(CFLAGS) $(INCLUDES) -o epstool $(OBJS) $(LIBS) 

clean:
	-$(RM) epstool.$(OBJ)
	-$(RM) gvceps.$(OBJ)
	-$(RM) dscparse.$(OBJ)
	-$(RM) dscutil.$(OBJ)

veryclean: clean
	-$(RM) epstool

install: epstool
	cp epstool $(BINDIR)
	chmod 755 $(BINDIR)/epstool
