# Copyright (C) 2000, Ghostgum Software Pty Ltd.  All rights reserved.
#  
# This file is part of GSview.
#  
# This program is distributed with NO WARRANTY OF ANY KIND.  No author
# or distributor accepts any responsibility for the consequences of using it,
# or for whether it serves any particular purpose or works at all, unless he
# or she says so in writing.  Refer to the GSview Free Public Licence 
# (the "Licence") for full details.
#  
# Every copy of GSview must include a copy of the Licence, normally in a 
# plain ASCII text file named LICENCE.  The Licence grants you the right 
# to copy, modify and redistribute GSview, but only under certain conditions 
# described in the Licence.  Among other things, the Licence requires that 
# the copyright notice and this notice be preserved on all copies.

# makefile.msc - for Microsoft Visual C++ 5.0
# EPSTOOL

CFLAGS=-D__WIN32__ -DEPSTOOL -I..\src -I.
CC=cl

OBJS=epstool.obj gvceps.obj gvcdsc.obj gvcfile.obj gvwgsver.obj

all: epstool.exe

.cpp.obj:
	$(CC) $(CFLAGS) -c $*.cpp

epstool.obj: epstool.cpp epstool.h ../src/gvcdsc.h ../src/gvcfile.h ../src/gvceps.cpp
	$(CC) -c $(CFLAGS) epstool.cpp

gvcdsc.obj: ../src/gvcdsc.cpp epstool.h ../src/gvcdsc.h ../src/gvcfile.h
	$(CC) -c $(CFLAGS) ../src/gvcdsc.cpp

gvcfile.obj: ../src/gvcfile.cpp ../src/gvcfile.h
	$(CC) -c $(CFLAGS) ../src/gvcfile.cpp

gvceps.obj: ../src/gvceps.cpp epstool.h ../src/gvcdsc.h ../src/gvcfile.h
	$(CC) -c $(CFLAGS) ../src/gvceps.cpp

gvwgsver.obj: ../src/gvwgsver.cpp
	$(CC) -c $(CFLAGS) ../src/gvwgsver.cpp

epstool.exe: $(OBJS)
	link /SUBSYSTEM:console /OUT:epstool.exe $(OBJS) user32.lib advapi32.lib 

veryclean: clean
	-del epstool.exe
	-del epstool2.exe

clean:
	-del epstool.map
	-del epstool.obj
	-del gvcdsc.obj
	-del gvcfile.obj
	-del gvceps.obj
	-del gvwgsver.obj
	-del epstool.ilk
	-del epstool.pdb
	-del files.txt

files.txt: makefile.msc
	echo epstool/epstool.cpp>files.txt
	echo epstool/epstool.h>>files.txt
	echo epstool/epstool.def>>files.txt
	echo epstool/epstool.htm>>files.txt
	echo epstool/makefile.msc>>files.txt
	echo epstool/makefile.os2>>files.txt
	echo epstool/makefile.tc>>files.txt
	echo epstool/makefile.unx>>files.txt
	echo src/LICENCE>>files.txt
	echo src/gvceps.cpp>>files.txt
	echo src/gvceps.h>>files.txt
	echo src/gvcdsc.cpp>>files.txt
	echo src/gvcdsc.h>>files.txt
	echo src/gvcfile.cpp>>files.txt
	echo src/gvcfile.h>>files.txt
	echo src/gvwgsver.cpp>>files.txt
	echo epstool.exe>>files.txt
	echo epstool2.exe>>files.txt
	echo epstool.htm>>files.txt


zip: all files.txt
	copy epstool.htm ..\epstool.htm
	copy epstool.exe ..\epstool.exe
	cd ..
	rename epstool2.exe epstool2.exe
	-del epstool.zip
	zip -@ epstool < epstool\files.txt
	cd epstool

tar:	zip
	unzip -o ..\epstool
	copy src\* epstool
	-del ..\epstool.tar
	cd epstool
	flip -u *.*
	cd ..
	tar -cvf ../epstool.tar epstool

