# Copyright (C) 1993-1996, Russell Lang.  All rights reserved.
#  
# This file is part of GSview.
#  
# This program is distributed with NO WARRANTY OF ANY KIND.  No author
# or distributor accepts any responsibility for the consequences of using it,
# or for whether it serves any particular purpose or works at all, unless he
# or she says so in writing.  Refer to the GSview Free Public Licence 
# (the "Licence") for full details.
#  
# Every copy of GSview must include a copy of the Licence, normally in a 
# plain ASCII text file named LICENCE.  The Licence grants you the right 
# to copy, modify and redistribute GSview, but only under certain conditions 
# described in the Licence.  Among other things, the Licence requires that 
# the copyright notice and this notice be preserved on all copies.

# makefile.os2
# EPSTOOL
# requires emx 0.9a
#
# edit COMPBASE and EMXPATH as required.

# set USE_EMX=0 for BCC
# set USE_EMX=1 for EMX/GCC
USE_EMX=1
# USE_OMF=1 for EMX/GCC with LINK386
USE_OMF=0

!if $(USE_EMX)
# EMX
DRIVE=c:
COMP=gcc
COMPBASE=$(DRIVE)\emx
EMXPATH=$(DRIVE)/emx
!if $(USE_OMF)
FLAGS=-Zomf -g -I. -I../src
OBJ=obj
!else
FLAGS=-g -I. -I../src
OBJ=o
!endif
!else
# BCC flags
COMP=bcc
COMPBASE=d:\bcos2
EMXPATH=d:/bcos2
FLAGS=-v -I$(INCDIR) -I../src -sm
OBJ=obj
!endif

# ICC flags
#COMP=icc
#COMPBASE=c:\ibmc
#EMXPATH=c:/ibmc
#FLAGS=/Gm /Ti /Sm /Ic:\toolkt20\c\os2h;c:\ibmc\include -DNO_MMOS2
#OBJ=obj

COMPDIR=$(COMPBASE)\bin
INCDIR=$(EMXPATH)/include
LIBDIR=$(EMXPATH)/lib


OBJS=epstool.$(OBJ) gvceps.$(OBJ) ps.$(OBJ)

all: epstool.exe

.c.$(OBJ):
	$(COMP) $(FLAGS) -DOS2 -DEPSTOOL -c $*.c


epstool.$(OBJ): epstool.c epstool.h ../src/ps.h

ps.$(OBJ): ../src/ps.c epstool.h ../src/ps.h
	$(COMP) $(FLAGS) -DOS2 -DEPSTOOL -c -o $*.$(OBJ) ../src/$*.c

gvceps.$(OBJ): ../src/gvceps.c epstool.h ../src/ps.h
	$(COMP) $(FLAGS) -DOS2 -DEPSTOOL -c -o $*.$(OBJ) ../src/$*.c

epstool.exe: $(OBJS) epstool.def
!if $(USE_EMX)
!if $(USE_OMF)
	$(COMP) $(FLAGS) -o epstool.exe $(OBJS) epstool.def
!else
	$(COMP) $(FLAGS) -o epstool.out $(OBJS)
	emxbind $(COMPDIR)\emxl.exe epstool.out epstool.exe
	del epstool.out
!endif
!else
	$(COMP) $(FLAGS) -eepstool.exe $(OBJS)
!endif

clean:
	-del epstool.$(OBJ)
	-del gvceps.$(OBJ)
	-del ps.$(OBJ)

veryclean: clean
	-del epstool.exe
	-del epstool2.exe

EPSFILES=\
 epstool/epstool.c\
 epstool/epstool.h\
 epstool/epstool.def\
 epstool/epstool.txt\
 epstool/epstest.cmd\
 epstool/makefile.os2\
 epstool/makefile.tc\
 epstool/makefile.unx

SRCFILES1=\
 src/LICENCE\
 src/gvceps.c\
 src/gvceps.h\
 src/PUBLIC\
 src/ps.c\
 src/ps.h

ZIPFILES=\
 epstool.exe\
 epstool.txt\
 $(EPSFILES)\
 $(SRCFILES1)

prezip:
	copy epstool.exe ..\epstool2.exe
	cd ..
	emxbind -s epstool2.exe
	cd epstool

zip: all
	copy epstool.txt ..
	copy epstool.exe ..
	emxbind -s ../epstool.exe
	cd ..
	-del epstool.zip
	zip epstool $(ZIPFILES)
	cd epstool

tar:	zip
	unzip -o ..\epstool
	copy src\* epstool
	-del ..\epstool.tar
	cd epstool
	flip -u *
	cd ..
	tar -cvf ../epstool.tar epstool
