# Copyright (C) 1993, 1994, Russell Lang.  All rights reserved.
#  
# This file is part of GSview.
#  
# This program is distributed with NO WARRANTY OF ANY KIND.  No author
# or distributor accepts any responsibility for the consequences of using it,
# or for whether it serves any particular purpose or works at all, unless he
# or she says so in writing.  Refer to the GSview Free Public Licence 
# (the "Licence") for full details.
#  
# Every copy of GSview must include a copy of the Licence, normally in a 
# plain ASCII text file named LICENCE.  The Licence grants you the right 
# to copy, modify and redistribute GSview, but only under certain conditions 
# described in the Licence.  Among other things, the Licence requires that 
# the copyright notice and this notice be preserved on all copies.

# makefile.unx
# EPSTOOL

RM=/bin/rm -f
SHELL=/bin/sh

BINDIR=/usr/local/bin
INCLUDES=-I/usr/openwin/include
LIBS=
DEFINES=-DUNIX -DEPSTOOL -DHAVE_UNISTD_H
OBJ=o
COMP=gcc

OBJS=epstool.$(OBJ) gvceps.$(OBJ) ps.$(OBJ)

all: epstool

.c.$(OBJ):
	$(COMP) $(INCLUDES) $(DEFINES) -c $*.c


epstool.$(OBJ): epstool.c epstool.h ps.h gvceps.h

ps.$(OBJ): ps.c epstool.h ps.h gvceps.h

gvceps.$(OBJ): gvceps.c epstool.h ps.h gvceps.h

epstool: $(OBJS)
	$(COMP) $(INCLUDES) -o epstool $(OBJS) $(LIBS) 

clean:
	-$(RM) epstool.$(OBJ)
	-$(RM) gvceps.$(OBJ)
	-$(RM) ps.$(OBJ)

veryclean: clean
	-$(RM) epstool

install: epstool
	cp epstool $(BINDIR)
	chmod 755 $(BINDIR)/epstool
