# Copyright (C) 2000, Ghostgum Software Pty Ltd.  All rights reserved.
#  
# This file is part of GSview.
#  
# This program is distributed with NO WARRANTY OF ANY KIND.  No author
# or distributor accepts any responsibility for the consequences of using it,
# or for whether it serves any particular purpose or works at all, unless he
# or she says so in writing.  Refer to the GSview Free Public Licence 
# (the "Licence") for full details.
#  
# Every copy of GSview must include a copy of the Licence, normally in a 
# plain ASCII text file named LICENCE.  The Licence grants you the right 
# to copy, modify and redistribute GSview, but only under certain conditions 
# described in the Licence.  Among other things, the Licence requires that 
# the copyright notice and this notice be preserved on all copies.

# makefile.msc - for Microsoft Visual C++ 5.0
# EPSTOOL

CFLAGS=-D__WIN32__ -DEPSTOOL -I..\src -I. -DSTDIO
CC=cl

OBJS=epstool.obj gvceps.obj dscparse.obj dscutil.obj gvwgsver.obj gvcfile.obj

all: epstool.exe

.c.obj:
	$(CC) $(CFLAGS) -c $*.c

epstool.obj: epstool.c epstool.h ../src/dscparse.h ../src/gvceps.c
	$(CC) -c $(CFLAGS) epstool.c

dscparse.obj: ../src/dscparse.c epstool.h ../src/dscparse.h
	$(CC) -c $(CFLAGS) ../src/dscparse.c

dscutil.obj: ../src/dscutil.c epstool.h ../src/dscparse.h
	$(CC) -c $(CFLAGS) ../src/dscutil.c

gvceps.obj: ../src/gvceps.c epstool.h ../src/dscparse.h
	$(CC) -c $(CFLAGS) ../src/gvceps.c

gvcfile.obj: ../src/gvcfile.c ../src/gvcfile.h
	$(CC) -c $(CFLAGS) ../src/gvcfile.c

gvwgsver.obj: ../src/gvwgsver.c
	$(CC) -c $(CFLAGS) ../src/gvwgsver.c

epstool.exe: $(OBJS)
	link /SUBSYSTEM:console /OUT:epstool.exe $(OBJS) user32.lib advapi32.lib 

veryclean: clean
	-del epstool.exe
	-del epstool2.exe

clean:
	-del epstool.map
	-del epstool.obj
	-del dscparse.obj
	-del dscutil.obj
	-del gvceps.obj
	-del gvwgsver.obj
	-del epstool.ilk
	-del epstool.pdb
	-del files.txt

files.txt: makefile.msc
	echo epstool/epstool.c>files.txt
	echo epstool/epstool.h>>files.txt
	echo epstool/epstool.def>>files.txt
	echo epstool/epstool.htm>>files.txt
	echo epstool/makefile.msc>>files.txt
	echo epstool/makefile.os2>>files.txt
	echo epstool/makefile.tc>>files.txt
	echo epstool/makefile.unx>>files.txt
	echo src/LICENCE>>files.txt
	echo src/gvceps.c>>files.txt
	echo src/gvceps.h>>files.txt
	echo src/dscparse.c>>files.txt
	echo src/dscutil.c>>files.txt
	echo src/dsc.h>>files.txt
	echo src/gvwgsver.c>>files.txt
	echo epstool.exe>>files.txt
	echo epstool2.exe>>files.txt
	echo epstool.htm>>files.txt


zip: all files.txt
	copy epstool.htm ..\epstool.htm
	copy epstool.exe ..\epstool.exe
	cd ..
	rename epstool2.exe epstool2.exe
	-del epstool.zip
	zip -@ epstool < epstool\files.txt
	cd epstool

tar:	zip
	unzip -o ..\epstool
	copy src\* epstool
	-del ..\epstool.tar
	cd epstool
	flip -u *.*
	cd ..
	tar -cvf ../epstool.tar epstool

