.nh
.TH "gsview" "1"
.SH "NAME"
gsview \- PostScript and PDF viewer
.SH "SYNTAX"
\fBgsview [options] [filename]\fR
.PP
Options are described in the GSview HTML help file.
.SH "DESCRIPTION"
\fBGSview\fR is a graphical interface for Ghostscript under MS-Windows,
OS/2 and Unix.  Ghostscript is an interpreter for the PostScript page 
description language used by laser printers.
For documents following the Adobe PostScript Document Structuring 
Conventions, \fBGSview\fR allows selected pages to be viewed or printed.
\fBGSview\fR requires Ghostscript 7.00 - 7.99.
.SH "AUTHOR"
Russell Lang, Ghostgum Software Pty Ltd.
.SH "SEE ALSO"
The \fBGSview\fR documentation is usually in the directory
/usr/share/doc/gsview-N.N, where N.N is the version number of \fBGSview\fR.
.PP
\fBgs (1)\fR, the Ghostscript program.
.PP
http://www.ghostgum.com.au/
.SH "COPYRIGHT"
.PP
Copyright 1993-2001 Ghostgum Software Pty Ltd
.PP
