#
#  Copyright (C) 1993-2000, Ghostgum Software Pty Ltd.  All rights reserved.
#  
# This file is part of GSview.
#  
# This program is distributed with NO WARRANTY OF ANY KIND.  No author
# or distributor accepts any responsibility for the consequences of using it,
# or for whether it serves any particular purpose or works at all, unless he
# or she says so in writing.  Refer to the GSview Free Public Licence 
# (the "Licence") for full details.
#  
# Every copy of GSview must include a copy of the Licence, normally in a 
# plain ASCII text file named LICENCE.  The Licence grants you the right 
# to copy, modify and redistribute GSview, but only under certain conditions 
# described in the Licence.  Among other things, the Licence requires that 
# the copyright notice and this notice be preserved on all copies.

# Partial makefile for language and version

# Language is English (en) or Deutsch (de) or French (fr) or Italian (it)
# This only applies to the utilties, not GSview itself.
LANGUAGE=en

# GSview version
GSVIEW_VERSION=34
GSVIEW_DOT_VERSION=3.4
GSVIEW_DATE=2000-07-29


gsvver.h: gvcver.mak
	echo /* gsvver.h - automatically generated by gvcver.mak */> gsvver.h
	echo #define GSVIEW_VERSION $(GSVIEW_VERSION)>> gsvver.h
	echo #define GSVIEW_DOT_VERSION "$(GSVIEW_DOT_VERSION)">> gsvver.h
	echo #define GSVIEW_DATE "$(GSVIEW_DATE)">> gsvver.h
